name: Close Pull Request

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Close PR if it is not from Dependabot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "The content of this repo is completely generated. Therefore PRs are not accepted. You can check the [issue templates](https://github.com/manami-project/anime-offline-database/issues/new/choose) if you want to report something."
            exit 0
          fi
          echo "Closing the PR as it's not from Dependabot."
          gh pr close ${{ github.event.pull_request.number }} --comment "Automatically closing this PR" --delete-branch
